---
title: "Survey Data Analysis Case Study"
author: "Bethany Gardner"
date: 08/29/2024
format:
  revealjs:
    embed-resources: true
    footer: bethanyhgardner/survey-analyst-case-study
    incremental: true
    slide-number: true
    theme: white
    
---

```{r}
#| label: setup

library(tidyverse)  # general data wrangling and plots
library(igraph)  # calculate flowchart positions
library(RColorBrewer)  # color scheme

theme_blue <- "#5692e4"  # revealjs theme blue
```

##  Why this project?

-   Using one of my dissertation experiments as a case study (published as [GitHub Repository](https://github.com/bethanyhgardner/dissertation/) and [Quarto Book](https://bethanyhgardner.github.io/dissertation/))
-   I've chosen to talk about this one because it involves the most data preprocessing/management steps, and I was in charge of all of them

## About the experiment

-   Studying language learning and processing mechanisms for singular *they*
-   Including pronouns on nametags and in introductions are common recommendations for creating a more gender-inclusive environment. We know it can affect people's perception of an environment, but does it also affect people's language *use*?
-   This is a testable hypothesis!

## About the experiment

-   Learned about a set of fictional characters (he/him, she/her, and they/them)
    *   Varied whether the introductions to the character explicitly stated their pronouns (*This is Alex, who uses they/them pronouns. They...*)
    *   Varied whether the nametags included pronouns
-   Speech production task eliciting possessive pronouns (*Alex gave the apple to their brother.*)
-   Survey about their demographics and attitudes about/experiences with singular *they*

## About the data

-   Audio data transcribed and annotated for which pronouns were produced & survey data for each participant
-   Do the nametag and introduction conditions affect accuracy producing singular *they*?
-   If production accuracy is internally reliable, is it predicted by demographics, language attitude, or language experience measures?


